const initialAchievements = [
  {
    id: "1",
    title: "Bem vindo!",
    notification:
      "Você escolheu a red pill, seus olhos foram abertos para viver com hábitos saudáveis.",
    description: "Conta criada",
    achieved: false,
    secret: false,
    image: "morpheus.svg",
  },
  {
    id: "2",
    title: "Olá Mr. Robot!",
    notification: "Elliot Alderson, é você?",
    description: "Acesse o DevTools de seu navegador.",
    achieved: false,
    secret: true,
    image: "fsociety-mask.svg",
  },
  {
    id: "3",
    title: "O primeiro passo.",
    notification: "Te vejo amanhã!",
    description: "Dê seu primeiro check-in",
    achieved: false,
    secret: false,
    image: "ticket.png",
  },
  {
    id: "4",
    title: "Um jedi completo.",
    notification: "A força, com você, está!",
    description: "Complete um hábito de cada categoria",
    achieved: false,
    secret: false,
    image: "yoda.svg",
  },
  {
    id: "5",
    title: "A primeira de muitas vitórias.",
    notification: "A primeira de muitas vitórias!",
    description: "Completou seu primeiro hábito",
    achieved: false,
    secret: false,
    image: "virtue.png",
  },
  {
    id: "6",
    title: "Bem, não era esse o plano...",
    notification:
      "Bem, não era esse o plano... Mas tudo bem, você consegue na próxima!",
    description: "Excluiu um hábito.",
    achieved: false,
    secret: true,
    image: "stress.png",
  },
  {
    id: "7",
    title: "O escolhido",
    notification: "Você está começando a acreditar.",
    description: "Completou um hábito de Corpo e mente saudáveis.",
    achieved: false,
    secret: false,
    image: "neo.svg",
  },
  {
    id: "8",
    title: "Grato.",
    notification: "Agradecer é o caminho para se ter uma vida em paz",
    description: "Completou Praticar a gratidão",
    achieved: false,
    secret: true,
    image: "peace-symbol.png",
  },
  {
    id: "9",
    title: "Mente e cérebro felizes.",
    notification: "Uma mente feliz é um cérebro feliz!",
    description: "Iniciou um hábito de Corpo e mente saudáveis.",
    achieved: false,
    secret: false,
    image: "brain.png",
  },
  {
    id: "10",
    title: "Bons sonhos",
    notification: "Tá na hora de dormir...",
    description: "Iniciou um hábito de Boa noite.",
    achieved: false,
    secret: false,
    image: "freedy-krueger.svg",
  },
  {
    id: "11",
    title: "Dorminhoco",
    notification: "Só de clicar nesse check-in já me deu um sono...",
    description: "Completou um hábito de Boa noite.",
    achieved: false,
    secret: false,
    image: "dreaming-in-bed.png",
  },
  {
    id: "12",
    title: "Chega de distrações!",
    notification: "Chega de distrações!",
    description: "Completou Desconecte-se do celular.",
    achieved: false,
    secret: true,
    image: "no-mobile.png",
  },
  {
    id: "13",
    title: "Começando a economizar.",
    notification: "De grão em grão...",
    description: "Criou um hábito de Me poupe.",
    achieved: false,
    secret: false,
    image: "egg.png",
  },
  {
    id: "14",
    title: "Papo cheio.",
    notification: "... A galinha enche o papo",
    description: "Completou um hábito de Me poupe",
    achieved: false,
    secret: false,
    image: "chicken.png",
  },
  {
    id: "15",
    title: "Desconto de 100%",
    notification: "Se eu não comprar nada, o desconto é bem maior!",
    description: "Completou Planejar gastos",
    achieved: false,
    secret: true,
    image: "money-box.png",
  },
  {
    id: "16",
    title: "Alguém vai beber o leite derramado!",
    notification:
      "Eu não acredito nisso, 49 centavos de leite derramado na minha mesa!",
    description: "Completou Monitorar gastos",
    achieved: false,
    secret: true,
    image: "milk-carton.png",
  },
  {
    id: "17",
    title: "20 milhões não da pra nada!",
    notification: "R$ 200.000/mês eu acho que consigo viver com tranquilidade.",
    description: "Completou 5 hábitos de Me poupe.",
    achieved: false,
    secret: true,
    image: "stack-of-money.png",
  },
  {
    id: "18",
    title: "Cuidando da casa.",
    notification: "Não vale jogar a sujeira em baixo do tapete!",
    description: "Criou um hábito Lar doce lar",
    achieved: false,
    secret: false,
    image: "home.svg",
  },
  {
    id: "19",
    title: "Sweet home.",
    notification: "Home sweet home",
    description: "Completou um hábito Lar doce lar.",
    achieved: false,
    secret: false,
    image: "home.gif",
  },
  {
    id: "20",
    title: "Groot.",
    notification: "I'am Groot !!!",
    description: "Criou o hábito Regar as plantas",
    achieved: false,
    secret: true,
    image: "groot.svg",
  },
  {
    id: "21",
    title: "Planta saudável.",
    notification: "Ta chovendo na minha horta",
    description: "Completou o hábito Regar as plantas.",
    achieved: false,
    secret: true,
    image: "irrigation.png",
  },
  {
    id: "22",
    title: "Vou varrendo.",
    notification: "Diga aonde você vai, que eu vou varrendo",
    description: "Completou o hábito Varrer o chão",
    achieved: false,
    secret: true,
    image: "broom.png",
  },
  {
    id: "23",
    title: "Mantendo o foco",
    notification: "Te desafio a ter mais foco que ele.",
    description: "Iniciou um hábito de Foco, Força e Fé",
    achieved: false,
    secret: false,
    image: "homer-simpson.svg",
  },
  {
    id: "24",
    title: "A força.",
    notification: "Seu foco é como de um jedi!",
    description: "Completou um hábito de Foco, Força e Fé",
    achieved: false,
    secret: false,
    image: "lightsaber.svg",
  },
  {
    id: "25",
    title: "Leitor assíduo",
    notification: "É, o livro era bem melhor.",
    description: "Completou Ler um capítulo de um livro",
    achieved: false,
    secret: true,
    image: "book-reading.png",
  },
  {
    id: "26",
    title: "Corte de calorias",
    notification: "Cookies? só se for pro cookies monster.",
    description: "Iniciou um hábito de Ficando em forma",
    achieved: false,
    secret: false,
    image: "cookie-monster.svg",
  },
  {
    id: "27",
    title: "Trapésio descendente.",
    notification: "BIRLLLL!!! TÁ SAINDO DA JAULA O MONSTRO",
    description: "Completou um hábito Ficando em forma.",
    achieved: false,
    secret: false,
    image: "we-can-do-it.png",
  },
  {
    id: "28",
    title: "Tá pago!",
    notification: "O de hoje tá pago!!!",
    description: "Primeiro check-in em Ficando em forma",
    achieved: false,
    secret: true,
    image: "muscle.png",
  },
];

export default initialAchievements;
